export const items = [
  "Release 6.5: New features and enhanc...",
  "Release 6.4: Hirefy: Precision Unleashed",
  "Release 6.3: Hirefy is Expanding...",
  "Release 6.2: Time for some Bug...",
  "Release 6.1: Augmented Reality Talent...",
  "Release 6.0: Augmented Reality Talent...",
  "Release 5.4: Bug Fixes and Performanc...",
  "Release 5.3: Simplified Job Posting...",
  "Release 5.2: Interactive Interview...",
  "Release 5.1: Responsive Design Tweaks...",
  "Release 5.0: Expanded Language...",
  "Release 4.3: Server Performance...",
  "Release 4.2: Intelligent Candidate...",
  "Release 4.1: Our Mobile app is on the...",
  "Release 4.0: Advanced Networking...",
  "Release 3.3: Personalized Skill...",
  "Release 3.2: Community-Reported Bug...",
  "Release 3.1: Getting ready for Mobile...",
  "Release 3.0: Our family is getting bigger",
  "Release 2.2: The importance of Consent",
  "Release 2.1: AI-Powered Skill Gap...",
  "Release 2.0: Cloud Infrastructure Scaling",
  "Release 1.4: Baby steps...",
  "Release 1.3: Proactive Community Bug...",
  "Release 1.2: User-Centric Performance...",
  "Release 1.1: Server Response Time...",
  "Release 1.0: Initial Launch: Navigating...",
];
